// Barrel APEX — generato da design-sync. Solo la superficie PUBBLICA del sito.
// Esclusi: Server Component async con fetch Airtable + GoogleAnalytics (non visuale).
// Il polyfill di process.env va PRIMA di ogni componente (vedi shims/process-env.ts).
import "./shims/process-env";
export { ApexCard } from "../src/components/apex/ApexCard";
export { ApexCta } from "../src/components/apex/ApexCta";
export { ApexFooter } from "../src/components/apex/ApexFooter";
export { ApexNavBar } from "../src/components/apex/ApexNavBar";
export { Countdown } from "../src/components/apex/Countdown";
export { FondaleVivo } from "../src/components/apex/FondaleVivo";
export { Grain } from "../src/components/apex/Grain";
export { Hud } from "../src/components/apex/Hud";
export { SectionHead } from "../src/components/apex/SectionHead";
export { StageProp } from "../src/components/apex/StageProp";
export { StageScene } from "../src/components/apex/StageScene";
export { Ticker } from "../src/components/apex/Ticker";
export { ApexLegalSection } from "../src/components/apex/legal/ApexLegalSection";
export { ApexLegalTableWrapper, ApexLegalTh, ApexLegalTd } from "../src/components/apex/legal/ApexLegalTable";
export { EchoStack } from "../src/components/apex/propkit/EchoStack";
export { Monolite209 } from "../src/components/apex/propkit/Monolite209";
export { RacingLine } from "../src/components/apex/propkit/RacingLine";
export { TargaDorsale } from "../src/components/apex/propkit/TargaDorsale";
export { TelemetriaGhost, Waveform } from "../src/components/apex/propkit/TelemetriaGhost";
export { Doodle } from "../src/components/apex/propkit/scuola/Doodle";
export { Sticker } from "../src/components/apex/propkit/scuola/Sticker";
export { Toppa } from "../src/components/apex/propkit/scuola/Toppa";
export { AltimetriaProfile } from "../src/components/apex/propkit/marathon/AltimetriaProfile";
export { ComeRaggiungerci } from "../src/components/home/ComeRaggiungerci";
export { HeroCampagne } from "../src/components/home/HeroCampagne";
export { HomeTicker } from "../src/components/home/HomeTicker";
export { MapEmbed } from "../src/components/home/MapEmbed";
export { PhotoPlaceholder } from "../src/components/home/PhotoPlaceholder";
export { SezioneAmatori } from "../src/components/home/SezioneAmatori";
export { SezioneMarathon } from "../src/components/home/SezioneMarathon";
export { SezioneScuola } from "../src/components/home/SezioneScuola";
export { ScuolaHero } from "../src/components/scuola/ScuolaHero";
export { SezioneAllenarsiACasa } from "../src/components/scuola/SezioneAllenarsiACasa";
export { SezioneComeIscriversi } from "../src/components/scuola/SezioneComeIscriversi";
export { SezioneCorsi } from "../src/components/scuola/SezioneCorsi";
export { SezioneFilosofia } from "../src/components/scuola/SezioneFilosofia";
export { SezioneGalleria } from "../src/components/scuola/SezioneGalleria";
export { SezioneKitScuola } from "../src/components/scuola/SezioneKitScuola";
export { SezioneMaestri } from "../src/components/scuola/SezioneMaestri";
export { SezioneSicurezza } from "../src/components/scuola/SezioneSicurezza";
export { ChiSiamoHero } from "../src/components/chi-siamo/ChiSiamoHero";
export { CosaSiamoOggi } from "../src/components/chi-siamo/CosaSiamoOggi";
export { Fondatori } from "../src/components/chi-siamo/Fondatori";
export { Timeline } from "../src/components/chi-siamo/Timeline";
export { BachecaFoto } from "../src/components/amatori/BachecaFoto";
export { ComeUnirsi } from "../src/components/amatori/ComeUnirsi";
export { DoveQuando } from "../src/components/amatori/DoveQuando";
export { SezioneValori } from "../src/components/amatori/SezioneValori";
export { CosaEla209 } from "../src/components/marathon-209/CosaEla209";
export { CtaMarathon } from "../src/components/marathon-209/CtaMarathon";
export { Edizioni } from "../src/components/marathon-209/Edizioni";
export { InfoPratiche } from "../src/components/marathon-209/InfoPratiche";
export { MarathonHero } from "../src/components/marathon-209/MarathonHero";
export { Percorso } from "../src/components/marathon-209/Percorso";
export { CtaContattaci } from "../src/components/diventa-maestro/CtaContattaci";
export { HeroManifesto } from "../src/components/diventa-maestro/HeroManifesto";
export { SezioneChiCerchiamo } from "../src/components/diventa-maestro/SezioneChiCerchiamo";
export { SezioneCosaFarai } from "../src/components/diventa-maestro/SezioneCosaFarai";
export { SezioneTI2 } from "../src/components/diventa-maestro/SezioneTI2";
export { ContactForm } from "../src/components/contatti/ContactForm";
export { ConsentProvider } from "../src/components/consent/ConsentProvider";
export { Switch } from "../src/components/consent/Switch";
// Schede di riferimento delle fondamenta (token resi visibili).
export { FondamentaTipografia } from "./fondamenta/FondamentaTipografia";
export { FondamentaColori } from "./fondamenta/FondamentaColori";
export { FondamentaSpaziature } from "./fondamenta/FondamentaSpaziature";
export { FondamentaAtomi } from "./fondamenta/FondamentaAtomi";
export { ApexStage } from './shims/ApexStage';
